name: "Find Minimum Required Rust Version"

description: "Runs cargo-msrv on multiple paths and finds the highest minimum Rust version required."
author: "derrix060"

branding:
  icon: "eye"
  color: "red"

inputs:
  paths:
    description: "Comma-separated list of paths to run cargo-msrv.  Defaults to the current directory"
    default: "."
  min:
    description: "Minimum Rust version to start searching from. Useful when Cargo.lock uses v4 format (requires 1.78.0+)."
    default: ""
  locked:
    description: "If true, passes --locked to cargo to enforce using Cargo.lock and prevent dependency re-resolution."
    default: "false"

outputs:
  highest-msrv:
    description: "The highest minimum Rust version required."
    value: ${{ steps.cargo-msrv.outputs.highest-msrv }}

runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: cargo

    - name: Install cargo-msrv
      shell: bash
      run: cargo install --locked cargo-msrv@0.18.4

    - name: Setup jq
      uses: dcarbone/install-jq-action@v3.2.0

    - name: Pre-fetch dependencies
      if: ${{ inputs.locked == 'true' }}
      shell: bash
      run: |
        # Pre-fetch dependencies to ensure cargo registry index is synced
        # and crates are cached before cargo-msrv runs with --locked
        IFS=',' read -r -a paths <<< "${{ inputs.paths }}"
        for path in "${paths[@]}"; do
          echo "Fetching dependencies for $path"
          cargo fetch --locked --manifest-path "${path}/Cargo.toml" || true
        done

    - name: Run cargo-msrv for each path
      id: cargo-msrv
      shell: bash
      run: |
        set -euxo pipefail

        # Split the input paths by commas
        IFS=',' read -r -a paths <<< "${{ inputs.paths }}"

        # Initialize the highest version variable
        highest_msrv="0.0.0"

        # Function to compare versions
        compare_versions() {
          if [[ "$1" == "$2" ]]; then
            echo 0
          elif [[ "$1" == "$(echo -e "$1\n$2" | sort -Vr | head -n1)" ]]; then
            echo 1
          else
            echo 2
          fi
        }

        # Build optional arguments
        min_arg=""
        if [[ -n "${{ inputs.min }}" ]]; then
          min_arg="--min ${{ inputs.min }}"
        fi

        locked_arg=""
        if [[ "${{ inputs.locked }}" == "true" ]]; then
          # The -- separator replaces the default cargo check command entirely,
          # so we must specify the full command including 'cargo check'
          locked_arg="-- cargo check --locked"
        fi

        # Loop through all paths and run cargo-msrv
        for path in "${paths[@]}"; do
          echo "Running cargo-msrv for $path"
          cargo msrv find --path "$path" --output-format json --no-log $min_arg $locked_arg 2>&1 | tee logs.txt
          version=$(tail -1 logs.txt | jq -r '.result.version')
          if [[ "$version" == "null" ]]; then
            echo "Could not find MSRV for $path"
            exit 1
          fi

          echo "Found MSRV $version for $path"

          # Compare and store the highest version
          result=$(compare_versions $highest_msrv $version)
          if [[ "$result" -eq "2" ]]; then
            echo "Found higher MSRV $version than $highest_msrv"
            highest_msrv=$version
          fi
        done

        echo "The highest MSRV is $highest_msrv"

        # Set output
        echo "highest-msrv=$highest_msrv" >> $GITHUB_OUTPUT
